---
- name: Create 
  hosts: localhost
  vars_files:
    - ./aws_vars.yml
    - group_vars/all.yml
    - group_vars/pass.yml
  gather_facts: false
  
  roles:
  - { role: code_deploy_ec2, tags: ["code_deploy_ec2"] }
  - { role: code_deploy_service, tags: ["code_deploy_service"] }
  - { role: ec2-instance-target-ec2-role, tags: ["target"] }
